# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, aligned to sys.path.insert(0, 'some_path')
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for local time
# timezone =

# max length of characters to encode a slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from the revision
# script.  Only required if the revision script explicitly imports
# other modules.
# sourceless = false

# version location specification; this defaults
# to migrations/versions.  When using multiple version
# directories, paths must be comma-delimited.
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions

# version path separator; as above we use ',' as the default,
# but this can be ',' or ' ' or ';' or any other character.
# version_path_separator = ,

# set to 'true' to search for newer revision files of the same version
# in a multi-directory setup
# recursive_version_check = false

# the output encoding used when writing new migration files
# output_encoding = utf-8


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

# format using "black" - used as an example, this requires 'black' to be installed
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILE

# format using "ruff" - used as an example, this requires 'ruff' to be installed
# hooks = ruff
# ruff.type = console_scripts
# ruff.entrypoint = ruff
# ruff.options = --force-exclude --fix REVISION_SCRIPT_FILE

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
